image: node:18

stages:
  - install
  - lint
  - test
  - build
  - deploy

variables:
  NODE_ENV: "production"
  NPM_CONFIG_CACHE: "$CI_PROJECT_DIR/.npm"

cache:
  key:
    files:
      - package-lock.json
  paths:
    - node_modules/
    - .npm/

install_dependencies:
  stage: install
  script:
    - npm ci
  artifacts:
    paths:
      - node_modules/
    expire_in: 1 hour

lint:
  stage: lint
  needs: [install_dependencies]
  script:
    - npm run lint
  allow_failure: false

test:
  stage: test
  needs: [install_dependencies]
  script:
    - npm test
    - npm run test:coverage
  coverage: '/Lines\s*:\s*(\d+\.\d+)%/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml
    paths:
      - coverage/
    expire_in: 30 days

build:
  stage: build
  needs: [lint, test]
  script:
    - npm run build
  artifacts:
    paths:
      - .next/
      - public/
    expire_in: 1 week
  only:
    - main
    - develop

deploy_production:
  stage: deploy
  needs: [build]
  script:
    - echo "Deploying to production..."
    - npm install -g vercel
    - vercel --token $VERCEL_TOKEN --prod
  environment:
    name: production
    url: https://your-app.vercel.app
  only:
    - main
  when: manual

deploy_staging:
  stage: deploy
  needs: [build]
  script:
    - echo "Deploying to staging..."
    - npm install -g vercel
    - vercel --token $VERCEL_TOKEN
  environment:
    name: staging
    url: https://staging-your-app.vercel.app
  only:
    - develop
